export const FILMS_COUNT_PER_STEP = 5;
export const FILMS_EXTRA_COUNT = 2;
export const MAX_LENGTH_DESCRIPTION = 140;
export const REGEXP_ALL_FILMS_COUNT = /\B(?=(\d{3})+(?!\d))/g;
export const LOCAL_COMMENT_DEFAULT = {emotion: '', comment: ''};
export const END_POINT = 'https://15.ecmascript.pages.academy/cinemaddict';
export const AUTHORIZATION = 'Basic 0K3RgtC+IPCfkJQg0L3QsCDRgdC80LXRhSE=';
export const MAIN_TITLE = 'All movies. Upcoming';
export const LOADING_TITLE = 'Loading...';
export const STATISTIC_BAR_HEIGHT = 50;
export const SHAKE_ANIMATION_TIMEOUT = 600;
export const SHAKE_ANIMATION_DURATION = SHAKE_ANIMATION_TIMEOUT / 1000;
export const TOAST_SHOW_TIME = 5000;
export const STORE_PREFIX = 'cinemaddict-localstorage';
export const STORE_VER = 'v15';
export const STORE_NAME = `${STORE_PREFIX}-${STORE_VER}`;
